### Variables
# Generate a token and set it here
@token = oat_MQ.QkJxZmlOY0V0RnUtWE9kR0M2QjdZVnVvWE12NDBONGNmS3F2ZFRDTDM1Mjc3NjMyMTU

### Generate a word
POST http://localhost:3333/word
Content-Type: application/json
Authorization: Bearer {{token}}

### Verify a letter
GET http://localhost:3333/word?letter=a
Content-Type: application/json
Authorization: Bearer {{token}}