### Variables
# Generate a token and set it here
@token = oat_Nw.WFZFbE4wMk5vMnRwOGk5N05VdHNFay1oZWg0R09LdzQ3bzZzMVBGTzE4MzM1MTA1MTY

### Generate a word
POST http://localhost:3333/word
Content-Type: application/json
Authorization: Bearer {{token}}

### Verify a letter
GET http://localhost:3333/word?letter=a
Content-Type: application/json
Authorization: Bearer {{token}}