### Variables
# Generate a token and set it here
@token = oat_MQ.UnpJYVRjUGJadmhxNnFuQVN2TUEzU0R0c3YxNVBBNTQ0bG51ZkV4RzE4OTA4OTg3Mjk

### Generate a word
POST http://localhost:3333/word
Content-Type: application/json
Authorization: Bearer {{token}}

### Verify a letter
GET http://localhost:3333/word?letter=a
Content-Type: application/json
Authorization: Bearer {{token}}